version: '3.4'

services:
  client:
    image: redis:6-alpine
    command: sleep 50000

#  m:
#    image: redis:6-alpine
#    volumes:
#      - "master:/data"
#    ports:
#      - "6379:6379"
# 
#  s:
#    image: redis:6-alpine
#    command: redis-server --slaveof m 6379
#    volumes:
#      - "slave:/data"
#    ports:
#      - "6380:6379"
  
  m:
    image: apache/kvrocks:2.3.0 
    command:  -c /kvrocks/conf/kvrocks.conf
    volumes:
      - "master:/data"
      - ./kvrocks-master.conf:/kvrocks/conf/kvrocks.conf
    ports:
      - "6379:6379"

  s:
    image: apache/kvrocks:2.3.0
    command:  -c /kvrocks/conf/kvrocks.conf
    volumes:
      - "slave:/data"
      - ./kvrocks-slave.conf:/kvrocks/conf/kvrocks.conf
    ports:
      - "6380:6379"
  
  se1:
    image: redis:6-alpine
    command: redis-server /redis/sentinel.conf --sentinel
    volumes:
      - "./sentinel.conf:/redis/sentinel.conf"
 
  se2:
    image: redis:6-alpine
    command: redis-server /redis/sentinel.conf --sentinel
    volumes:
      - "./sentinel.conf:/redis/sentinel.conf"
 
  se3:
    image: redis:6-alpine
    command: redis-server /redis/sentinel.conf --sentinel
    volumes:
      - "./sentinel.conf:/redis/sentinel.conf"

volumes:
  master: {}
  slave: {}
